// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMmO2H4sUceMqfLdUEAycqbfd-BVn2Z2Q',
    appId: '1:246883194844:web:5e35a3ab48636cee29e119',
    messagingSenderId: '246883194844',
    projectId: 'quiz-app-zolo',
    authDomain: 'quiz-app-zolo.firebaseapp.com',
    databaseURL: 'https://quiz-app-zolo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-app-zolo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDboHbUkNqBntkkkTLCD5pVCgMlVGzjd8U',
    appId: '1:246883194844:android:db0b002f6ef114a429e119',
    messagingSenderId: '246883194844',
    projectId: 'quiz-app-zolo',
    databaseURL: 'https://quiz-app-zolo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-app-zolo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOW9orlUdKZ1gj9hBEfnwwhTYE9xMEFkA',
    appId: '1:246883194844:ios:058249930109722529e119',
    messagingSenderId: '246883194844',
    projectId: 'quiz-app-zolo',
    databaseURL: 'https://quiz-app-zolo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-app-zolo.appspot.com',
    androidClientId: '246883194844-bm1qp6r0jid8jo8p04jrcfjavvo6kqhq.apps.googleusercontent.com',
    iosClientId: '246883194844-408k89e44l3oru2v4bg1112nj63frldo.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOW9orlUdKZ1gj9hBEfnwwhTYE9xMEFkA',
    appId: '1:246883194844:ios:2aa5b2f725b3156829e119',
    messagingSenderId: '246883194844',
    projectId: 'quiz-app-zolo',
    databaseURL: 'https://quiz-app-zolo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quiz-app-zolo.appspot.com',
    androidClientId: '246883194844-bm1qp6r0jid8jo8p04jrcfjavvo6kqhq.apps.googleusercontent.com',
    iosClientId: '246883194844-csf04co23enbn4hi1498psplc0c8pl5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp.RunnerTests',
  );
}
